language: node_js

node_js:
  - "node"
  - "lts/*"

before_install:
  - npm install
  - npm install -g codecov

script:
  - npm run type:check
  - npm run prettier:check
  - npm test -- --coverage # enforce 100% coverage when testing against the latest react-select
  - npm run test:all-versions
  - npm run build
  - npm pack

after_success:
  - codecov
